baseURL: 'http://example.org/'
languageCode: en-us
title: jnierth
theme: "alpha"
Paginate: 5
menu:
  main:
    - identifier: project
      name: Project
      url: /projects/
      weight: 2
    - identifier: design
      name: Design
      url: /designs/
      weight: 3
    - identifier: faq
      name: About
      url: /about/
      weight: 4
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 5