baseURL: 'http://jessica/'
languageCode: en-us
title: jnierth
theme: "alpha"
Paginate: 4
DefaultContentLanguage: de
defaultContentLanguageInSubdir: true
taxonomies:
  applicationtype: applicationtypes
  category: categories
  genre: genres
  tag: tags
languages:
  de:
    description: "Web Engineer mit Leidenschaft für Web-Architekturen und wartbarem Code. Passion für Automatisierung
     von Prozessen und Arbeit an Projekten mit praktischem Hintergrund."
    languageName: Deutsch
    title: Jessica Nierth - Web-Entwickler
    weight: 1
    menu:
      main:
        - url: /projekte/
          name: Projekte
          weight: 1
        - url: /de/designs/
          name: Design
          weight: 2
        - url: /de/kontakt/
          name: Kontakt
          weight: 3
    taxonomies:
      programmiersprache: programmiersprachen
  en:
    description: "Web Engineer with a passion for clean, maintainable code and work on useful tools, web-applications or -sites."
    languageName: English
    title: Jessica Nierth - Web-Engineer
    weight: 2
    menu:
      main:
        - url: /projects/
          name: Projects
          weight: 1
        - url: /designs/
          name: Design
          weight: 2
        - url: /contact/
          name: Contact
          weight: 3
    taxonomies:
      programminglanguage: programminglanguages
